//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarteModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarteModel()
        {
            this.employe_carte = new HashSet<employe_carte>();
        }
    
        public int id { get; set; }
        public string reference { get; set; }
        public string type_poste { get; set; }
        public string status { get; set; }
        public string status_carte { get; set; }
        public System.DateTime date_creation { get; set; }
        public System.DateTime date_fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employe_carte> employe_carte { get; set; }
    }
}
