//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employe()
        {
            this.employe_carte = new HashSet<employe_carte>();
            this.reunion_employe = new HashSet<reunion_employe>();
        }
    
        public int id { get; set; }
        public string Nom_Prenom { get; set; }
        public string matricule_Emp { get; set; }
        public string matricule_W { get; set; }
        public string Email { get; set; }
        public string Responsable { get; set; }
        public int role { get; set; }
        public int departement { get; set; }
    
        public virtual Departement Departement1 { get; set; }
        public virtual Role Role1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employe_carte> employe_carte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reunion_employe> reunion_employe { get; set; }
    }
}
