//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionCartesEntities2 : DbContext
    {
        public GestionCartesEntities2()
            : base("name=GestionCartesEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departement> Departement { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<CarteModel> CarteModel { get; set; }
        public virtual DbSet<employe_carte> employe_carte { get; set; }
        public virtual DbSet<reunion_employe> reunion_employe { get; set; }
        public virtual DbSet<Reunions> Reunions { get; set; }
        public virtual DbSet<Salles> Salles { get; set; }
    }
}
